[general]
import = [
    "themes/catppuccin-mocha.toml"
]
working_directory = "C:/Users/<user>"

[window]
opacity = 0.90
decorations = "None"
padding.x = 10
padding.y = 10
dynamic_padding = true

[terminal]
shell = "pwsh"

[env]
TERM = "xterm-256color"

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
size = 12


[cursor]
style.shape = "Underline"
style.blinking = "On"